name: prayer_reminder
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Notifications
  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_linux: ^5.0.0
  
  # Internationalization
  intl: ^0.20.1
  
  # Local storage
  shared_preferences: ^2.0.15
  
  # Location and sensors
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  sensors_plus: ^6.1.1
  
  # Network requests
  http: ^1.2.2
  
  # Logging
  logger: ^2.5.0
  
  # Audio playback
  audioplayers: ^6.1.0
  
  # Timezone support
  timezone: ^0.10.0
  
  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Material Icons
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/audio/
    - assets/images/compass.png
    - assets/audio/adhan_makkah.mp3
    - assets/audio/adhan_madinah.mp3
    - assets/audio/adhan_alaqsa.mp3
